"$schema" = 'https://starship.rs/config-schema.json'

format = """
(#2e3440)\
[  ](bg:#2e3440 fg:#d8dee9)\
[](bg:#3b4252 fg:#2e3440)\
$directory\
[](bg:#434c5e fg:#3b4252)\
$git_branch\
$git_status\
[](bg:#4c566a fg:#434c5e)\
$time\
[ ](fg:#4c566a)\
\n$character"""

[directory]
style = "bg:#3b4252 fg:#d8dee9"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"dev" = ""

[git_branch]
symbol = ""
style = "bg:#434c5e"
format = '[[ $symbol $branch ](bg:#434c5e fg:#d8dee9)]($style)'

[git_status]
style = "bg:#434c5e"
format = '[[($all_status$ahead_behind )](bg:#434c5e fg:#d8dee9)]($style)'

[nodejs]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[php]
disabled = true

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#4c566a"
format = '[[  $time ](bg:#4c566a fg:#e5e9f0)]($style)'
